import type { Category } from '@wikispeedrun/shared';

// Curated pool for start/goal articles: well-known, link-rich pages that make
// good race targets. Random difficulty bypasses this with true-random articles.
// Titles are canonical English Wikipedia titles.

export const ARTICLE_POOL: readonly string[] = [
  // Places
  'France',
  'Japan',
  'China',
  'India',
  'Brazil',
  'Egypt',
  'Australia',
  'Canada',
  'Russia',
  'Germany',
  'Italy',
  'Spain',
  'Mexico',
  'United States',
  'United Kingdom',
  'Paris',
  'London',
  'Tokyo',
  'Rome',
  'New York City',
  'Mount Everest',
  'Amazon rainforest',
  'Sahara',
  'Antarctica',
  'Great Wall of China',
  'Eiffel Tower',
  'Statue of Liberty',
  'Great Pyramid of Giza',
  // History
  'Roman Empire',
  'Ottoman Empire',
  'French Revolution',
  'American Civil War',
  'World War II',
  'Renaissance',
  'Industrial Revolution',
  'Vikings',
  'Samurai',
  'Knight',
  'Castle',
  'Ancient Egypt',
  'Middle Ages',
  // People
  'Napoleon',
  'Julius Caesar',
  'Cleopatra',
  'Genghis Khan',
  'Abraham Lincoln',
  'Albert Einstein',
  'Isaac Newton',
  'Marie Curie',
  'Charles Darwin',
  'Nikola Tesla',
  'Leonardo da Vinci',
  'William Shakespeare',
  'Wolfgang Amadeus Mozart',
  'Ludwig van Beethoven',
  'Vincent van Gogh',
  'Pablo Picasso',
  'Michelangelo',
  'The Beatles',
  'Elvis Presley',
  'Muhammad Ali',
  // Science & nature
  'Sun',
  'Moon',
  'Earth',
  'Mars',
  'Jupiter',
  'Black hole',
  'Milky Way',
  'Universe',
  'Gravity',
  'Evolution',
  'DNA',
  'Oxygen',
  'Gold',
  'Electricity',
  'Volcano',
  'Dinosaur',
  'Ocean',
  'Photosynthesis',
  'Antibiotic',
  'Vaccine',
  // Animals
  'Dog',
  'Cat',
  'Horse',
  'Elephant',
  'Lion',
  'Tiger',
  'Shark',
  'Whale',
  'Penguin',
  'Octopus',
  'Bee',
  'Eagle',
  'Wolf',
  'Bear',
  // Food & drink
  'Cheese',
  'Bread',
  'Rice',
  'Potato',
  'Banana',
  'Chocolate',
  'Coffee',
  'Tea',
  'Beer',
  'Wine',
  'Sushi',
  'Pizza',
  'Hamburger',
  'Ice cream',
  'Honey',
  // Culture & things
  'Music',
  'Jazz',
  'Rock music',
  'Guitar',
  'Piano',
  'Film',
  'Television',
  'Video game',
  'Chess',
  'Olympic Games',
  'Association football',
  'Basketball',
  'Star Wars',
  'Harry Potter',
  'The Lord of the Rings',
  'Batman',
  'Mickey Mouse',
  'Lego',
  'Christmas',
  'Halloween',
  'Dragon',
  'Zeus',
  'Piracy',
  // Technology & ideas
  'Computer',
  'Internet',
  'Robot',
  'Artificial intelligence',
  'Rocket',
  'Train',
  'Bicycle',
  'Car',
  'Airplane',
  'Ship',
  'Telephone',
  'Photography',
  'Money',
  'Democracy',
  'Mathematics',
  'Philosophy',
  'Language',
  'Time',
  'Color',
] as const;

export interface CategoryPair {
  start: string;
  goal: string;
}

// Themed start/goal pairs, one bucket per category (excluding 'any', which uses
// the flat pool above). Each pair is hand-picked so the start article links
// toward the goal within a hop or two — famous, link-rich pages that are never
// dead-ends — so a category round is always winnable. Kept small and playful.
export const CATEGORY_PAIRS: Record<Exclude<Category, 'any'>, readonly CategoryPair[]> = {
  science: [
    { start: 'Albert Einstein', goal: 'Physics' },
    { start: 'Charles Darwin', goal: 'Evolution' },
    { start: 'Isaac Newton', goal: 'Gravity' },
    { start: 'DNA', goal: 'Biology' },
    { start: 'Marie Curie', goal: 'Chemistry' },
  ],
  history: [
    { start: 'Napoleon', goal: 'French Revolution' },
    { start: 'Julius Caesar', goal: 'Roman Empire' },
    { start: 'Cleopatra', goal: 'Ancient Egypt' },
    { start: 'Genghis Khan', goal: 'Mongol Empire' },
  ],
  geography: [
    { start: 'France', goal: 'Paris' },
    { start: 'Japan', goal: 'Tokyo' },
    { start: 'Egypt', goal: 'Nile' },
    { start: 'Mount Everest', goal: 'Nepal' },
  ],
  'pop-culture': [
    { start: 'The Beatles', goal: 'Rock music' },
    { start: 'Star Wars', goal: 'Science fiction' },
    { start: 'Harry Potter', goal: 'J. K. Rowling' },
    { start: 'Batman', goal: 'DC Comics' },
  ],
};
