// Curated pool for start/goal articles: well-known, link-rich pages that make
// good race targets. Hard mode bypasses this with true-random articles.
// Titles are canonical English Wikipedia titles.

export const ARTICLE_POOL: readonly string[] = [
  // Places
  'France',
  'Japan',
  'China',
  'India',
  'Brazil',
  'Egypt',
  'Australia',
  'Canada',
  'Russia',
  'Germany',
  'Italy',
  'Spain',
  'Mexico',
  'United States',
  'United Kingdom',
  'Paris',
  'London',
  'Tokyo',
  'Rome',
  'New York City',
  'Mount Everest',
  'Amazon rainforest',
  'Sahara',
  'Antarctica',
  'Great Wall of China',
  'Eiffel Tower',
  'Statue of Liberty',
  'Great Pyramid of Giza',
  // History
  'Roman Empire',
  'Ottoman Empire',
  'French Revolution',
  'American Civil War',
  'World War II',
  'Renaissance',
  'Industrial Revolution',
  'Vikings',
  'Samurai',
  'Knight',
  'Castle',
  'Ancient Egypt',
  'Middle Ages',
  // People
  'Napoleon',
  'Julius Caesar',
  'Cleopatra',
  'Genghis Khan',
  'Abraham Lincoln',
  'Albert Einstein',
  'Isaac Newton',
  'Marie Curie',
  'Charles Darwin',
  'Nikola Tesla',
  'Leonardo da Vinci',
  'William Shakespeare',
  'Wolfgang Amadeus Mozart',
  'Ludwig van Beethoven',
  'Vincent van Gogh',
  'Pablo Picasso',
  'Michelangelo',
  'The Beatles',
  'Elvis Presley',
  'Muhammad Ali',
  // Science & nature
  'Sun',
  'Moon',
  'Earth',
  'Mars',
  'Jupiter',
  'Black hole',
  'Milky Way',
  'Universe',
  'Gravity',
  'Evolution',
  'DNA',
  'Oxygen',
  'Gold',
  'Electricity',
  'Volcano',
  'Dinosaur',
  'Ocean',
  'Photosynthesis',
  'Antibiotic',
  'Vaccine',
  // Animals
  'Dog',
  'Cat',
  'Horse',
  'Elephant',
  'Lion',
  'Tiger',
  'Shark',
  'Whale',
  'Penguin',
  'Octopus',
  'Bee',
  'Eagle',
  'Wolf',
  'Bear',
  // Food & drink
  'Cheese',
  'Bread',
  'Rice',
  'Potato',
  'Banana',
  'Chocolate',
  'Coffee',
  'Tea',
  'Beer',
  'Wine',
  'Sushi',
  'Pizza',
  'Hamburger',
  'Ice cream',
  'Honey',
  // Culture & things
  'Music',
  'Jazz',
  'Rock music',
  'Guitar',
  'Piano',
  'Film',
  'Television',
  'Video game',
  'Chess',
  'Olympic Games',
  'Association football',
  'Basketball',
  'Star Wars',
  'Harry Potter',
  'The Lord of the Rings',
  'Batman',
  'Mickey Mouse',
  'Lego',
  'Christmas',
  'Halloween',
  'Dragon',
  'Zeus',
  'Piracy',
  // Technology & ideas
  'Computer',
  'Internet',
  'Robot',
  'Artificial intelligence',
  'Rocket',
  'Train',
  'Bicycle',
  'Car',
  'Airplane',
  'Ship',
  'Telephone',
  'Photography',
  'Money',
  'Democracy',
  'Mathematics',
  'Philosophy',
  'Language',
  'Time',
  'Color',
] as const;
